import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import '@/styles/index.scss';

const jost = Jost({
  subsets: ['latin'],
  variable: '--jost',
});

export const metadata: Metadata = {
  title: 'YoTours',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased relative`}>
        {children}
      </body>
    </html>
  );
}

/**
 * Application works fine after removing: react-slick, slick-carousel
 */
